# Generated by Django 3.1.2 on 2020-10-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Futuro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='futuro', verbose_name='Imagen')),
                ('show', models.BooleanField(default=False, verbose_name='Mostrar')),
            ],
            options={
                'verbose_name': 'futuro',
                'verbose_name_plural': 'futuros',
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='prevision', verbose_name='Imagen')),
                ('show', models.BooleanField(default=False, verbose_name='Mostrar')),
            ],
            options={
                'verbose_name': 'previsión',
                'verbose_name_plural': 'previsión',
            },
        ),
    ]
